edukamoz/Pallas-3semester

package-lock.json, package.json, src/app/cadastrar/cadastrar.component.css, src/app/cadastrar/cadastrar.component.html, src/app/cadastrar/cadastrar.component.spec.ts
Adicionado @media, e feito alterações para no HTML  e CSS para deixar deixar pagina responsiva
Como alterações nas unidades de media de px para %, em , rem etc Para o site ficar mais adequado a telas de montires de 17" para cima e notebook de 12.5" até 17.6"
=> Cadastrar Responsivo 1

src/app/login/login.component.css, src/app/login/login.component.html
Feito alterações na pagina de Login para ficar responsivo a tela de notebooks de 12.5" até 17.6" ou tela de monitores de 17"  ou acima.
Como: @media, e alterações nas unidades de medida de px , para %, rem , em, etc.
=> Login Responsivo 1

src/app/cadastrar/cadastrar.component.css, src/app/cadastrar/cadastrar.component.html, src/app/cadastrar/cadastrar.component.ts
Adicionando campo de nome do usuário na pagina de cadastrar e suas validações.
=> AdicionandoAbanomeUsuario

src/app/main/main.component.html, src/app/main/main.component.ts, src/app/recursos/recursos.component.css
ajustes de responsividade e layout na página de recursos
- Adicionada responsividade para notebooks e monitores usando flex-wrap e media queries
- Inserido espaçamento entre colunas principais com gap e ajuste de largura máxima
- Separação vertical entre botões com margin
- Alinhamento vertical interno das divs com flex-direction: column
- Adicionado padding-top na seção .recursos para distanciamento do header
=> Recursos Responsivo

src/app/main/main.component.html, src/app/main/main.component.ts, src/app/recursos/recursos.component.html, src/app/recursos/recursos.component.ts, src/index.html
- Implementada navegação por teclado com tabindex e aria-labels nos links
- Adicionado suporte à leitura por voz com SpeechSynthesis API para títulos
- Integrado plugin VLibras para intérprete de LIBRAS no app global
- Melhorias em roles e aria-labelledby para melhor suporte a leitores de tela
=> adicionar acessibilidade na página Recursos

package-lock.json, src/app/cadastrar/cadastrar.component.html, src/app/cadastrar/cadastrar.component.ts
feat: adicionar acessibilidade na página Recursos
- Implementada navegação por teclado com tabindex e aria-labels nos links
- Adicionado suporte à leitura por voz com SpeechSynthesis API para títulos
- Melhorias em roles e aria-labelledby para melhor suporte a leitores de tela
=> adicionar acessibilidade na página Cadastrar

src/app/login/login.component.css, src/app/login/login.component.html, src/app/login/login.component.ts
Implementada navegação por teclado com tabindex e labels apropriadas
Adicionados atributos ARIA para suporte a leitores de tela
Integrado suporte à leitura por voz do título via SpeechSynthesis com checagem segura para evitar erros no servidor
Corrigido uso incorreto de aria-disabled em botões, usando somente disabled
Ajustado estilo do botão CADASTRAR para manter fundo branco e aparência normal mesmo quando desabilitado
Melhorias gerais de usabilidade e feedback visual nos inputs e botões
=> acessibilidade e estilo da página Login

src/app/home-main/home-main.component.css, src/app/home-main/home-main.component.html, src/app/home-main/home-main.component.ts
- Implementado carrossel com 5 membros da equipe, exibindo imagem, nome e função
- Estilização adicionada ao CSS de home-main para adaptar o layout do carrossel
- Ajustado HTML de home-main para incluir a seção "Nossa Equipe"
=> CarrosselEquipe Home-Main

src/app/cadastrar/cadastrar.component.css, src/app/duvidas/duvidas.component.css, src/app/login/login.component.css, src/app/recuperar-senha/recuperar-senha.component.css, src/app/recuperar-senha/recuperar-senha.component.html, src/app/recuperar-senha/recuperar-senha.component.ts
Criação da página de recuperação de senha com layout responsivo e melhorias visuais
- Estruturada a página de recuperação de senha utilizando Angular e Reactive Forms
- Adicionado formulário com validação de e-mail e exibição de mensagens de erro
- Ajustado o label "Digite seu e-mail:" para uma apresentação mais limpa e acessível
- Estilizada a mensagem de confirmação após envio do código, com destaque no e-mail e tempo restante
- Responsividade aplicada para dispositivos menores
- Acessibilidade básica com foco visível implementada
=> Criação Pagina Recuperar Senha

src/app/recuperar-senha/recuperar-senha.component.css, src/app/recuperar-senha/recuperar-senha.component.html, src/app/recuperar-senha/recuperar-senha.component.ts
- Adicionada navegação completa por teclado para facilitar o uso sem mouse
- Inclusão de atributos aria-label em botões e inputs para melhor suporte a leitores de tela
- Implementado botão de áudio para leitura por voz do título da página usando SpeechSynthesis API
- Ajustado layout para colocar o ícone de áudio ao lado do título "RECUPERAR SENHA" de forma agradável
- Adicionado tooltips (aria-describedby + title) para leitura do que cada elemento faz ao passar o mouse
- Ajustes finos no CSS para manter a harmonia visual e acessibilidade
=> AcessibilidadeRecuperar-Senha

src/app/header/header.component.css
Ajustada a responsividade do header usando unidades relativas (rem) e media queries para melhor adaptação em diferentes tamanhos de tela, mantendo o design original e melhorando a usabilidade em notebooks e monitores.
=> Responsividade na Header

src/app/header/header.component.css, src/app/header/header.component.html, src/app/header/header.component.ts
- Utiliza SpeechSynthesis API para anunciar o texto dos links ao hover
- Mantém navegação por teclado com tabindex e roles adequados
- Melhora atributos ARIA para suporte aprimorado a leitores de tela
- Acessibilidade aprimorada para usuários com deficiência visual ou auditiva
=> Acessibilidade no Header

src/app/footer/footer.component.css
- Footer agora usa display flex na classe .row para distribuir as colunas uniformemente.
- As colunas .col-md-4 foram configuradas para flex-grow, flex-shrink e largura mínima, garantindo responsividade e melhor uso do espaço.
- Padding do footer ajustado para unidades relativas (rem) mantendo o design original.
- Adicionado box-sizing: border-box para evitar overflow.
- Mantida responsividade para dispositivos móveis, com colunas empilhando em telas menores.
=> Tornando Footer responsivo

src/app/footer/footer.component.css
erros , nao foi o commit
- Footer agora usa display flex na classe .row para distribuir as colunas uniformemente.
- As colunas .col-md-4 foram configuradas para flex-grow, flex-shrink e largura mínima, garantindo responsividade e melhor uso do espaço.
- Padding do footer ajustado para unidades relativas (rem) mantendo o design original.
- Adicionado box-sizing: border-box para evitar overflow.
- Mantida responsividade para dispositivos móveis, com colunas empilhando em telas menores. Quer que eu ajude com algo mais?
=> Footer consertado

src/app/header/header.component.css, src/app/header/header.component.html, src/app/header/header.component.ts
- Implementada funcionalidade de text-to-speech usando Web Speech API
- Ao passar o mouse sobre os links do menu, o texto é lido em voz alta
- Ao clicar nos links, o texto também é lido antes da navegação
- Mantida a navegação por teclado e estilo original intactos
- Melhorada acessibilidade da header com feedback auditivo
=> consertando oque nao foi no commit

src/app/main/main.component.ts, src/app/sete-erros/sete-erros.component.css, src/app/sete-erros/sete-erros.component.html, src/app/sete-erros/sete-erros.component.spec.ts, src/app/sete-erros/sete-erros.component.ts
corrigido para o novo backe-end
=> sete-erros

src/app/home-main/home-main.component.css, src/app/home-main/home-main.component.html
Adiciona seção Missão, Visão e Valores na home
- Inclui nova seção logo abaixo do carrossel da equipe com os textos de Missão, Visão e Valores alinhados horizontalmente.
- Aplica estilo de fundo semi-transparente para destacar o conteúdo sem perder o visual da página.
- Ajusta o espaçamento entre os blocos para melhor apresentação visual.
- Mantém responsividade e alinhamento adequados para notebooks e monitores.
=> CriacaoMissaoVisaoValores

src/app/home-main/home-main.component.css
Ajustes na seção Missão, Visão e Valores para melhorar a responsividade e eliminar a rolagem horizontal.
- Alterado o layout da .mvv-section para permitir quebra de linha com flex-wrap, evitando overflow.
- Tornado os itens .mvv-item flexíveis, com largura mínima e máxima para melhor adaptação em diferentes telas.
- Ajustado espaçamento (gap) para não exceder a largura disponível.
- Removida a rolagem horizontal forçada, configurando overflow-x: hidden para evitar barras de rolagem desnecessárias.
- Melhorias nos media queries para que a seção fique legível e organizada em notebooks e monitores.
Essas alterações mantêm o design original, melhoram a usabilidade e a experiência do usuário em dispositivos maiores e intermediários.
=> MissaoVisaoValores Responsivo

src/app/home-main/home-main.component.html, src/app/home-main/home-main.component.ts
- Adiciona atributos tabindex para garantir foco nos elementos interativos e importantes para navegação por teclado
- Implementa leitura em voz alta ao passar o mouse ou clicar nos elementos-chave usando a Web Speech API (pt-BR)
- Mantém o design visual intacto, focando em acessibilidade
- Melhora a experiência para usuários que utilizam teclado e leitores de tela
=> Acessibilidade na HomeMain

src/app/duvidas/duvidas.component.css, src/app/duvidas/duvidas.component.html
Página de dúvidas atualizada:
- Adicionado botão com ícone SVG de interrogação
- Corrigido espaçamento abaixo do header
- Estilizado para acessibilidade e foco por teclado
- Melhorada responsividade para notebooks e monitores
=> Melhorando a responsividade de duvidas

src/app/ranking/ranking.component.html, src/app/ranking/ranking.component.spec.ts, src/app/ranking/ranking.component.ts
- Implementada leitura por voz ao passar o mouse sobre elementos com descrição
- Adicionado suporte à navegação por teclado com uso de tabindex
- Corrigido erro "document is not defined" com verificação de execução no browser (isPlatformBrowser)
- Mantida a estrutura e design original da página
=> Acessibilidade no ranking

src/app/desafios/desafios.component.html, src/app/desafios/desafios.component.ts
- Adicionados atributos tabindex="0" a elementos de texto e botões para inclusão na ordem de tabulação
- Incluídos aria-labels para melhorar a descrição dos botões por leitores de tela
- Implementada função `falar(texto: string)` usando a API nativa `speechSynthesis` no TypeScript
- Eventos (mouseenter) adicionados para acionar leitura de conteúdo ao passar o mouse sobre títulos, descrições e botões
=> Desafios Acessivel
